-- 183. Customers Who Never Order




SELECT NAME AS CUSTOMERS
  FROM CUSTOMERS C
      ,ORDERS    O
 WHERE C.ID = O.CUSTOMERID(+)
       AND O.CUSTOMERID IS NULL;


SELECT C.NAME AS CUSTOMERS 
  FROM CUSTOMERS C 
 WHERE C.ID NOT IN (SELECT CUSTOMERID FROM ORDERS O);